services:
    nginx:
        build: ./dockerfiles/nginx
        ports:
            - '8000:80'
        volumes:
            - './dockerfiles/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro'
            - './dockerfiles/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro'
            - '.:/var/www/tw_app'
        container_name: tw_app_nginx
        depends_on:
          - php
    php:
        build:
            context: .
            dockerfile: dockerfiles/php/Dockerfile
        volumes:
          - .:/var/www/tw_app
        container_name: tw_app_php
        deploy:
          resources:
            limits:
              memory: 512M
            reservations:
              memory: 128M
        depends_on:
          - db

    node:
        build:
          context: .
          dockerfile: dockerfiles/node/Dockerfile
        container_name: tw_app_node
        ports:
          - "5173:5173"
        volumes:
          - .:/var/www/tw_app
          - /var/www/tw_app/node_modules
        environment:
          - NODE_ENV=development
        deploy:
          resources:
            limits:
              memory: 512M
    db:
        image: 'postgres:17.9-alpine'
        container_name: tw_app_db
        ports:
            - '5433:5432'
        environment:
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
            POSTGRES_DB: '${DB_DATABASE}'
        deploy:
          resources:
            limits:
              memory: 1024M
    pgadmin:
        image: 'dpage/pgadmin4:9.12'
        container_name: tw_app_pgadmin
        ports:
            - '5434:80'
        environment:
            PGADMIN_DEFAULT_EMAIL: '${PGADMIN_EMAIL}'
            PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_DEFAULT_PASSWORD}'
            PMA_HOST: db

        depends_on:
          - db
